spring:
    application:
        name: authorization-server  
    datasource: 
        driverClassName: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/userservice?autoreconnect=true"
        password: "root"
        username: "root"
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        max-active: 15
        max-idle: 10
        max-wait: 8000
config:
    oauth2:
        privateKey: <private - key>
        publicKey: <public-key>
        clientid: talk2amareswaran
        clientSecret: talk@amareswaran
